# DNA-seq Variant Calling Pipeline Configuration - Test Run

samples:
  - sample1

reference:
  genome: "/home/sdodl001_odu_edu/references/genomes/hg38/hg38.fa"
  known_sites: "/home/sdodl001_odu_edu/references/known_sites/Homo_sapiens_assembly38.dbsnp138.vcf.gz"

snpeff_genome: "hg38"

trim:
  min_length: 50
  quality_cutoff: 20

align:
  threads: 4

variant_calling:
  threads: 2
  min_quality: 20

filtering:
  QD: 2.0
  FS: 60.0
  MQ: 40.0
  MQRankSum: -12.5
  ReadPosRankSum: -8.0
